spring:
  profiles:
    active: dev
#配置日志级别和日志路径 只将mapper包下的级别调整为debug的
logging:
  path: d:/log
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
server:
  port: 80
my:
  file:
    path: E:\wx\storage\fetch\
mybatis:
  type-handlers-package: com.cskaoyan.mall.mybatis
pagehelper:
  helper-dialect: mysql
