#数据库配置 采用默认数据库
spring:
  profiles:
    active: dev
  resources:
    static-locations: file:${myfile.img-path}
#配置日志级别和日志路径 只将mapper包下的级别调整为debug的
logging:
  path: d:/log
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
server:
  port: 80
#my:
#  file:
#    path: E:\wx\storage\fetch\
mybatis:
  type-handlers-package: com.cskaoyan.mall.mybatis
pagehelper:
  helper-dialect: mysql
myfile:
  img-path: d:/wx/storage/
  img-prefix: http://localhost
aliyun:
  access-key-id: LTAI4Fr5gfYhcVjLMqeRGbuT
  access-secret: IrkcHu6dZyrjPZRushgO76P5392HJ1
aliyun-sms:
  region-id: cn-hangzhou
  sign-name: 王道训练营
  template-code: SMS_173765187
user:
  default-avatar: /e/e/e/6/f/b/8/6/05dbd596-91ad-42e8-8c5b-6585dd2a9636-11.jpg